Application/urls.py
from django.urls import path

from .views import (
    ApplicationCreateView,
    ApplicationDeleteView,
    ApplicationDetailView,
    ApplicationUpdateView,
    MyApplicationsView,
    ApplicationApprovalAcceptedView,
    ApplicationRejectView,
    CheckoutView
    # Ratings,
  
)
app_name = 'applications'
urlpatterns = [
    # path('',JobListView.as_view(),name='jobs'),
    path(
        "application-details/<uuid:slug>",
        ApplicationDetailView.as_view(),
        name="application-details",
    ),
    path("apply-job/<slug>", ApplicationCreateView.as_view(), name="apply-job"),
    path(
        "update-application/<slug>",
        ApplicationUpdateView.as_view(),
        name="update-application",
    ),
    path('delete-application/<pk>',ApplicationDeleteView.as_view(),name='delete-application'),
    path("my-applications/", MyApplicationsView.as_view(), name="my-applications"),
   path('accept-job/<uuid:pk>/', ApplicationApprovalAcceptedView.as_view(), name='accept-job'),
    path('reject-application/<uuid:pk>/', ApplicationRejectView.as_view(), name='reject-application'),
    path("checkout/<slug>", CheckoutView.as_view(), name="checkout")
    # path("ratings/<uuid:slug>/",Ratings,name="ratings")
   
    
]

Job/urls.py
from django.urls import path

from .views import (
    JobCreateView,
    JobDeleteView,
    JobDetailView,
    JobListView,
    JobUpdateView,
    MyJobListView,
    SavedJobListView,
    savedJob,
    JobsByUserView,
    JobsByCategoryView,
    JobsByTagView,
    JobApplicationsListView,
    JobFilterView,
    ApplicationApprovalView,
    ApplicationCancelView,
    # MakePaymentView,
    # ApplicantRatings,
    ApplicantRatingsViews,
    # initiate_stk_push,
    # get_access_token,
    # CheckoutView,
    ComplaintsCreateView,
    JobDoneView
   
)

urlpatterns = [
    path("", JobListView.as_view(), name="jobs"),
    path("job-details/<slug>", JobDetailView.as_view(), name="job-details"),
    path("add-jobs/", JobCreateView.as_view(), name="add-jobs"),
    path("update-job/<slug>", JobUpdateView.as_view(), name="update-job"),
    path("delete-job/<slug>", JobDeleteView.as_view(), name="delete-job"),
    path("save-job/<slug>", savedJob, name="save-job"),
    path("saved-jobs/", SavedJobListView.as_view(), name="saved-jobs"),
    path("my-jobs/", MyJobListView.as_view(), name="my-jobs"),
    path("jobs-filter/", JobFilterView.as_view(), name="jobs-filter"),
    path("user-jobs/<username>", JobsByUserView.as_view(), name="user-jobs"),
    path("category-jobs/<slug>", JobsByCategoryView.as_view(), name="category-jobs"),
    path("tag-jobs/<slug>", JobsByTagView.as_view(), name="tag-jobs"),
    path('job/<slug>/applications/', JobApplicationsListView.as_view(), name='job-applications'),
    path('approve-application/<uuid:pk>',ApplicationApprovalView.as_view(),name='approve-application'),     
    path('application/<uuid:pk>/cancel/', ApplicationCancelView.as_view(), name='cancel-application'),
    path('application/<uuid:pk>/done/', JobDoneView.as_view(), name='job-done'),
    # path('make-payment/', MakePaymentView, name='make-payment'),
    # path("lipa-na-mpesa/", initiate_stk_push, name="lipa-na-mpesa"),
    # path("access_token/", get_access_token, name="access_token"),
    path('ratings/<profile_slug>/<application_slug>/ratings',ApplicantRatingsViews.as_view(),name="ratings"),
    path("complaints/<slug>", ComplaintsCreateView.as_view(), name="complaints")
    # path("checkout/<slug>", CheckoutView.as_view(), name="checkout")
     
]

Technical/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import handler404
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.defaults import page_not_found
from Page.sitemaps import StaticViewSitemap
from Job.sitemaps import JobSitemap
sitemaps={
    "jobs":JobSitemap,
    "static":StaticViewSitemap
}
urlpatterns = [
    path('admin/defender/', include('defender.urls')), # defender admin
    path('admin/', admin.site.urls),
    path("jobs/", include("Job.urls")),
    path("marketing/" , include("Marketing.urls")),
    path("blogs/", include("Blog.urls")),
    path("applications/", include("Application.urls")),
    path("", include("Page.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
#    path('mpesa/', include(mpesa_urls)),
    path("__debug__/", include("debug_toolbar.urls")),
    path("profile/", include("Account.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("accounts/", include("allauth.urls")),
    path('hijack/', include('hijack.urls')),
    path('sitemap.xml',sitemap,{"sitemaps":sitemaps},name="django.contrib.sitemaps.views.sitemap"),
    
    # path("hitcount/", include(("hitcount.urls", "hitcount"), namespace="hitcount")),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 ='Page.views.error_404'
handler500 ='Page.views.error_500'

Application/models.py
from django.db import models
from ckeditor.fields import RichTextField
import uuid
from Job.models import Job
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext as _

# Create your models here.
class Application(models.Model):
    """Model definition for Application."""

    # TODO: Define fields here
    uuid = models.UUIDField(
         primary_key = True,
         default = uuid.uuid4,
         editable = False)
    user = models.ForeignKey(User,related_name='user_application', on_delete=models.CASCADE,db_index=True)
    job = models.ForeignKey(Job, related_name='job_application', on_delete=models.CASCADE,db_index=True)
    charge = models.IntegerField(_("Fees (ksh)"))    
    description = RichTextField(_("Why You charge Above Fees!"))
    status = models.CharField(default='Pending', max_length=50, db_index=True)
    approved_canceled_time = models.DateTimeField(_("Approved / Rejected time"), blank=True, null=True)
    created = models.DateTimeField( auto_now_add=True)

    class Meta:
        """Meta definition for Application."""

        verbose_name = 'Application'
        verbose_name_plural = 'Applications'
        ordering =['-approved_canceled_time']
        unique_together =['user','job']

    def __str__(self):
        """Unicode representation of Application."""
        return self.charge

    # def save(self):
    #     """Save method for Application."""
    #     pass

    def get_absolute_url(self):
        """Return absolute url for Application."""
        return reverse ('application-details', kwargs={'slug': self.uuid})

    # TODO: Define custom methods here

Application/forms.py
from django import forms 
from .models import Application
from Job.models import Job
from ckeditor.widgets import CKEditorWidget
class ApplicationForm(forms.ModelForm):
    """Form definition for Application."""
    description = (forms.CharField(label="Why You charge Above Fees !",widget=CKEditorWidget(attrs={'class':'form-control''required'}),))
    class Meta:
        """Meta definition for Applicationform."""

        model = Application
        fields = ('charge','description')
        label ={
            "description":"Why You charge Above Fees!"
        }
        widget ={
            'charge':forms.NumberInput(attrs={'class':'form-select charge''required'}),
            # 'job': forms.HiddenInput(), 
            
        }
    # def __init__(self, *args, **kwargs):
    #     slug = kwargs.pop('slug')
    #     super().__init__(*args, **kwargs)
    #     self.fields['job'].queryset = Job.objects.filter(slug=slug)

class ApplicationEditForm(forms.ModelForm):
    """Form definition for Application."""
    description = (forms.CharField(label="Why You charge Above Fees !",widget=CKEditorWidget(attrs={'class':'form-control''required'}),))
    class Meta:
        """Meta definition for Applicationform."""

        model = Application
        fields = ('charge','description')
        widget ={
            'charge':forms.NumberInput(attrs={'class':'form-select charge''required'}),
            # 'job': forms.HiddenInput(), 
            
        }

Application/views.py
from typing import Any, Optional

from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db import models
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect 
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
    TemplateView
)
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from Job.models import Job
from  django.core.mail import EmailMessage
from .forms import ApplicationEditForm, ApplicationForm
from .models import Application
from django.template.loader import render_to_string
from twilio.rest import Client 
from .tasks import send_email_notification,send_sms_notification
from datetime import datetime
# Create your views here.


class ApplicationCreateView(LoginRequiredMixin,SuccessMessageMixin, CreateView):
    model = Application
    template_name = "applications/add-application.html"
    form_class = ApplicationForm
    success_message = "Job Application Success!"

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs['slug'] = self.kwargs['slug']  # pass job slug to form
    #     # kwargs['job'] = get_object_or_404(Job, slug=self.kwargs['slug'])
    #     return kwargs

    def form_valid(self, form):
        f = form.save(commit=False)
        f.user = self.request.user
        slug = self.kwargs["slug"]
        f.job = Job.objects.get(slug=slug)
        f.save()
        return super(ApplicationCreateView, self).form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy("applications:my-applications")


class ApplicationDetailView(LoginRequiredMixin,DetailView):
    model = Application
    template_name = "applications/application-detail.html"
    context_object_name = "application"
    slug_field = "uuid"
    slug_url_kwarg = "slug"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class MyApplicationsView(LoginRequiredMixin, ListView):
    model = Application
    template_name = "applications/my-applications.html"
    context_object_name = "applications"
    paginate_by = 1000

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.select_related("user", "job")
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["paginator"] = Paginator(context["object_list"], self.paginate_by)
        return context


class ApplicationUpdateView(LoginRequiredMixin,UpdateView):
    model = Application
    template_name = "applications/update-applications.html"
    form_class = ApplicationEditForm

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        obj = get_object_or_404(
            queryset, uuid=self.kwargs.get("slug"), user=self.request.user
        )

        return obj

    def get_success_url(self):
        return reverse_lazy("applications:my-applications")


class ApplicationDeleteView(DeleteView):
    model = Application
    template_name = "applications/delete-application.html"

    def get_success_url(self):
        return reverse_lazy("applications:my-applications")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user, pk=self.kwargs["pk"])







class ApplicationRejectView(LoginRequiredMixin, UserPassesTestMixin,UpdateView):
    model = Application
    fields = ["status"]
    template_name_suffix = "_reject_form"
    def test_func(self):
        application = self.get_object()
        return self.request.user == application.user
    
    def form_valid(self, form):
        job = self.object.job
        new_status = form.cleaned_data["status"]
        
        if new_status == "Rejected": #and self.object.status == "Accepted":
            job.status = "Open"
            Application.objects.filter(job=job, status="Not Accepted").exclude(
                pk=self.object.pk
            ).update(status="Pending")
            # sending email notification
            job_owner_email =self.object.job.user.email
            # job_owner_email='victorobwaku@gmail.com'
            subject = 'Approved Application Rejected'
            context ={
                'job':job,
                'application': self.get_object(),
                'applicant':self.get_object().user
            }
            message = render_to_string('emails/reject-accepted-application.html',context)           
            send_email_notification.delay(subject,message,job_owner_email)
            print(job_owner_email,job.title)
           
            
            # sending sms notification
            # twilio_message = f"Congratulations! Your application for the job '{job.title}' has been accepted."  # Compose the message
            # job_owner_phone_number="9876667"
            # send_sms_notification.delay(twilio_message,job_owner_phone_number)
        else:
            self.object.status = new_status
            self.object.approved_canceled_time= datetime.now()

        self.object.save()
        job.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse(
            "applications:my-applications")

   
class ApplicationApprovalAcceptedView(LoginRequiredMixin, UserPassesTestMixin,UpdateView):
    model = Application
    fields = ["status"]
    template_name_suffix = "_accept_form"
    
    def test_func(self):
        application = self.get_object()
        return self.request.user == application.user
    
    def form_valid(self, form):
        job = self.object.job
        new_status = form.cleaned_data["status"]
       
        if new_status == "AcceptJob": #and self.object.status == "Accepted":
            job.status = "In Progress"
            Application.objects.filter(job=job, status="Not Accepted").exclude(
                pk=self.object.pk
            ).update(status="Failed")
            
            # sending email notification
            job_owner_email =self.get_object().job.user.email
            # job_owner_email='victorobwaku@gmail.com'
            subject = 'Application Accepted'
            context ={
                'job':job,
                'application': self.object,
                'applicant':self.object.user
            }
            message = render_to_string('emails/accept-accepted-application.html',context)
            send_email_notification.delay(subject,message,job_owner_email)
            print(job_owner_email,job.title)
            
            # sending sms notification
            
            # twilio_message = f"Congratulations! Your application for the job '{job.title}' has been accepted."  # Compose the message
            # job_owner_phone_number="9876667"
            # send_sms_notification.delay(twilio_message,job_owner_phone_number)
        else:
            self.object.status = new_status
            self.object.approved_canceled_time= datetime.now()

        self.object.save()
        job.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse(
            "applications:my-applications"
        )

# def Ratings(request):
#      return (render,'ratings/ratings.html')
class CheckoutView(TemplateView):
    model = Application
    template_name = "payments/checkout.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["application"] = get_object_or_404(Application, uuid=self.kwargs.get('slug'))
        return context

templates/applications/add-application.html
{% extends 'base.html' %}
{% block title %} Job Application {% endblock title %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
   <div>
        <div class="main-content">

                <div class="page-content">

                                   
 <div class="breadcrumbs overlay  mt-1" >
<div class="container">
<div class="row align-items-center">
<div class="col-lg-6 col-md-6 col-12">
<div class="breadcrumbs-content">
<h1 class="page-title">Apply Job</h1>

</div>
</div>
<div class="col-lg-6 col-md-6 col-12">
<ul class="breadcrumb-nav float-sm-start float-lg-end float-md-end">
<li><a class="text-decoration-none" href="{% url 'home' %}">Home</a></li>
<li><a class="text-decoration-none" href="{% url 'jobs' %}">Jobs</a></li>
<li>Apply Job</li>
</ul>
</div>
</div>
</div>
</div>
                    <!-- START JOB-LIST -->
                    <section class="section" style="padding-top:0px;padding-bottom:0px;"> 
                          <div class="add-blog">
                        <div class="container">
                          
                            <div class="row">
                            <div class="row justify-content-center pt-3 mt-3">
                                <div class="col-lg-7">
                                    <div class="section-title text-center mb-4 pb-2">
                                        <h4 class="title"> Job Application Form</h4>
                                        <p class="text-muted mb-1">Post a job to tell us about your project. We'll quickly match you
                                            with the right freelancers.</p>
                                    </div>
                                </div><!--end col-->
                            </div><!--end row-->
                                <div class="col-lg-10 mx-auto">
                                     
                                   <form action="" method="post" enctype="multipart/form-data" class="p-5 mb-3 mt-4 border rounded-3 bg-white">
    {% csrf_token %}
    {{form | crispy }}
    
    <div class="d-grid gap-2 col-6 mx-auto pt-2">
    <button type="submit" class="btn btn-success">Submit </button>
    </div>
</form> 
                                    
                                </div><!--end col-->

                            </div><!--end row-->

                    
                        </div><!--end container-->
                    </section>
                    <!-- END JOB-form -->

                    
                </div>
                <!-- End Page-content -->

                

               
</div>
                
            </div>
            <!-- end main content-->

    </div>

 

<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

{% endblock content %}
    

templates/applications/application-detail.html
{% extends 'base.html' %}
{% load social_share %}
{% load hitcount_tags %}
{% block title %} Application Details {% endblock title %}

{% block content %}
<div>
     <div class="main-content">

                <div class="page-content">

                                     <div class="breadcrumbs overlay  mt-1" >
<div class="container">
<div class="row align-items-center">
<div class="col-lg-6 col-md-6 col-12">
<div class="breadcrumbs-content">
<h1 class="page-title">Application Details</h1>

</div>
</div>
<div class="col-lg-6 col-md-6 col-12">
<ul class="breadcrumb-nav float-sm-start float-lg-end float-md-end">
<li><a href="{% url 'home' %}">Home</a></li>
<li> <a href="{% url 'jobs' %}">Jobs</a> </li>
<li> <a href="{% url 'applications:my-applications' %}">My Applications</a> </li>
<li>Application Details</li>
</ul>
</div>
</div>
</div>
</div>
       

                    <!-- START JOB-DEATILS -->
                    <section class="section">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-8 mx-auto">
                                    <div class="card job-detail overflow-hidden shadow-lg p-3 mb-5 bg-body rounded">
                                     
                                        <div class="card-body p-4">
                                            <div>
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <h5 class="mb-1">{{application.job.title}}</h5>
                                                       
                                                    </div><!--end col-->
                                                   
                                                </div><!--end row-->    
                                            </div>

                                            <div class="mt-4">
                                                <div class="row g-2">
                                                   
                                                  
                                                    <div class="col-lg-4">
                                                        <div class="border p-3">
                                                            <p class="text-muted fs-13 mb-0">Status</p>
                                                            <p class="fw-medium mb-0"><span class="badge rounded-pill text-bg-warning">{{application.status}}</span>
</p>
                                                        </div>
                                                    </div>
                                                    
                                                </div>
                                            </div><!--end Experience-->

                                            <div class="mt-4">
                                                <h5 class="mb-3"> <span >Charge</span> </h5>
                                                <div class="job-detail-desc mt-1 text-muted">
                                                    <p class="text-muted mb-0">ksh {{application.charge}}</p>
                                                </div>
                                            </div>

                                            <div class="mt-4">
                                                <h5 class="mb-3 ">  <span >Reasons For the charge </span></h5>
                                                <div class="job-detail-desc mt-2 text-muted">
                                                   {{application.description}}
                                                </div>
                                            </div>
                                            
                                           

                                           

                                                    {% if user.is_authenticated and application.user == request.user %}
  
                                            <div class="mt-4 pt-3 flex-sm-wrap ">
                                                <ul class="list-inline mb-0 d-flex justify-content-around">
                                                    <li class="list-inline-item mt-1">
                                                        <a href="{% url 'applications:delete-application' application.uuid %}" class="btn btn-sm btn-outline-danger">Delete</a>
                                                    </li>
                                                    <li class="list-inline-item mt-1">
<a href="{% url 'applications:update-application' application.uuid %}" class="btn btn-sm btn-outline-primary">Edit</a>
                                                    </li>
                                                    

                                                   
                                                    
                                                     
                                                </ul>
                                            </div>

                                            {% endif %}
                                        </div><!--end card-body-->
                                    </div><!--end job-detail-->

                                    
                                </div><!--end col-->

                               
                            </div><!--end row-->
                        </div><!--end container-->
                    </section>
                    <!-- START JOB-DEATILS -->

                   

                </div>
                <!-- End Page-content -->

</div>


{% endblock content %}
    

templates/applications/application-details.html
{% extends 'base.html' %}
{% block title %} Job Details {% endblock title %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    
<div class="container">
    <div class="row">
        <div class="col-8">

<hr>
<p>job :  <a href="{% url 'job-details' application.job.slug %}">{{application.job.title}}</a>  </p>
<p>charge :{{application.charge}} </p>
<p>description : {{application.description}}</p>
<p>status : {{application.status}}</p>

<a href="{% url 'update-application' application.uuid %}" class="btn btn-primary">Update</a>
<a href="" class="btn btn-danger"> delete</a>
<hr>

<br><br><br><br><br>
        </div>
    </div>
</div>



{% endblock content %}
    

templates/applications/my-applications.html
{% extends 'base.html' %}
{% block title %} My Applications {% endblock title %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block content %}

     <!-- Begin page -->
        <div>

          

          
            <div class="main-content" style="min-height:100vh;">

                <div class="page-content">

                        <div class="breadcrumbs overlay  mt-1" >
<div class="container">
<div class="row align-items-center">
<div class="col-lg-6 col-md-6 col-12">
<div class="breadcrumbs-content">
<h1 class="page-title">My Applications</h1>

</div>
</div>
<div class="col-lg-6 col-md-6 col-12">
<ul class="breadcrumb-nav float-sm-start float-lg-end float-md-end">
<li><a href="{% url 'home' %}">Home</a></li>
<li> <a href="{% url 'jobs' %}">Jobs</a> </li>

<li>My Applications</li>
</ul>
</div>
</div>
</div>
</div>

                    <!-- START CANDIDATE-GRID -->
                    <section class="section">
                        <div class="container-fluid mx-2">
                          <div class="row"> <div class="col-md-11 mx-auto">
                            <table id="my-applications" class="table  table-sm table-striped  nowrap" style="width:100%">
        <caption>My Applications</caption>
                                <thead >
            <tr>
                <th>Reference ID</th>               
                {% comment %} <th>Job Status</th> {% endcomment %}
                <th>Charge</th>
                <th>Application Status</th>
                <th>Application Date</th>
                <th>Actions</th>
                <th>Canceled/Approved Time</th>
                <th> </th>
            </tr>
        </thead>
        <tbody class="table-group-divider  text-muted" style="font-size:15px;">
            {% for application in applications %}
            <tr>
                <td> <a href="{{application.job.get_absolute_url}}" class="text-decoration-none">{{application.job.reference_id}}</a> </td>
             
                {% comment %} <td>{{application.job.status}}</td> {% endcomment %}
                <td> ksh {{application.charge |intcomma}}</td>
                <td> 
                {% if application.job.status == "Done" %}
                    <span class="badge rounded-pill text-bg-success"> Done </span>
                    {% elif application.status == "Rejected" %}
                    <span class="badge rounded-pill text-bg-danger"> {{application.status}} </span>

                    {% elif application.status == "Accepted" %}
                     <span class="badge rounded-pill text-bg-warning"> Waiting </span>

                    {% else %}
 {{application.status}}
                {% endif %}
                    
                
                <td >{{application.created}}</td>
                <td >
                <div class="d-flex flex-row justify-content-around ">
{% comment %} {% if application.status == 'AcceptJob' %}
    <form method="POST" action="">
        {% csrf_token %}
        <input type="hidden" name="status" value="AcceptJob">
        <button type="submit" class="btn btn-sm btn-success">Request Payments </button>
    </form>
{% endif %} {% endcomment %}
    
{% if application.status == 'Accepted' %}
    <form method="POST" action="{% url 'applications:accept-job' application.uuid %}">
       
        {% csrf_token %}
        <input type="hidden" name="status" value="AcceptJob">
        <button type="submit" class="btn btn-sm btn-secondary">Accept</button>
    </form>

    <form method="POST" action="{% url 'applications:reject-application' application.uuid %}">
        {% csrf_token %}
        <input type="hidden" name="status" value="Rejected">
        <button type="submit" class="btn btn-sm btn-warning">Reject</button>
    </form>
{% endif %}
</div>               
</td>
                <td>{{application.approved_canceled_time}}</td>
                <td >
                    <div class="d-flex justify-content-around align-items-center">
                    <a href="{% url 'applications:update-application' application.uuid %}" class="link-primary"><i class="mdi mdi-pencil"></i></a>
<a href="{% url 'applications:delete-application' application.uuid %}" class="link-danger"> <i class="uil uil-trash-alt"></i></a>
<a href="{% url 'applications:application-details' application.uuid %}" class="link-info"> <i class="mdi mdi-eye"></i></a>
    
                    </div>
</td>
            </tr>
            {% empty %}
            {% endfor %}
            
           
         
        </tbody>
    </table>

             </div> </div>              

                        </div><!--end container-->
                    </section>
                    <!-- END CANDIDATE-GRID -->

                   

                </div>
                <!-- End Page-content -->

               
            </div>
            <!-- end main content-->

        </div>




{% endblock content %}
    