Application/urls.py
from django.urls import path

from .views import (
    ApplicationCreateView,
    ApplicationDeleteView,
    ApplicationDetailView,
    ApplicationUpdateView,
    MyApplicationsView,
    ApplicationApprovalAcceptedView,
    ApplicationRejectView,
    CheckoutView
    # Ratings,
  
)
app_name = 'applications'
urlpatterns = [
    # path('',JobListView.as_view(),name='jobs'),
    path(
        "application-details/<uuid:slug>",
        ApplicationDetailView.as_view(),
        name="application-details",
    ),
    path("apply-job/<slug>", ApplicationCreateView.as_view(), name="apply-job"),
    path(
        "update-application/<slug>",
        ApplicationUpdateView.as_view(),
        name="update-application",
    ),
    path('delete-application/<pk>',ApplicationDeleteView.as_view(),name='delete-application'),
    path("my-applications/", MyApplicationsView.as_view(), name="my-applications"),
   path('accept-job/<uuid:pk>/', ApplicationApprovalAcceptedView.as_view(), name='accept-job'),
    path('reject-application/<uuid:pk>/', ApplicationRejectView.as_view(), name='reject-application'),
    path("checkout/<slug>", CheckoutView.as_view(), name="checkout")
    # path("ratings/<uuid:slug>/",Ratings,name="ratings")
   
    
]

Job/urls.py
from django.urls import path

from .views import (
    JobCreateView,
    JobDeleteView,
    JobDetailView,
    JobListView,
    JobUpdateView,
    MyJobListView,
    SavedJobListView,
    savedJob,
    JobsByUserView,
    JobsByCategoryView,
    JobsByTagView,
    JobApplicationsListView,
    JobFilterView,
    ApplicationApprovalView,
    ApplicationCancelView,
    # MakePaymentView,
    # ApplicantRatings,
    ApplicantRatingsViews,
    # initiate_stk_push,
    # get_access_token,
    # CheckoutView,
    ComplaintsCreateView,
    JobDoneView
   
)

urlpatterns = [
    path("", JobListView.as_view(), name="jobs"),
    path("job-details/<slug>", JobDetailView.as_view(), name="job-details"),
    path("add-jobs/", JobCreateView.as_view(), name="add-jobs"),
    path("update-job/<slug>", JobUpdateView.as_view(), name="update-job"),
    path("delete-job/<slug>", JobDeleteView.as_view(), name="delete-job"),
    path("save-job/<slug>", savedJob, name="save-job"),
    path("saved-jobs/", SavedJobListView.as_view(), name="saved-jobs"),
    path("my-jobs/", MyJobListView.as_view(), name="my-jobs"),
    path("jobs-filter/", JobFilterView.as_view(), name="jobs-filter"),
    path("user-jobs/<username>", JobsByUserView.as_view(), name="user-jobs"),
    path("category-jobs/<slug>", JobsByCategoryView.as_view(), name="category-jobs"),
    path("tag-jobs/<slug>", JobsByTagView.as_view(), name="tag-jobs"),
    path('job/<slug>/applications/', JobApplicationsListView.as_view(), name='job-applications'),
    path('approve-application/<uuid:pk>',ApplicationApprovalView.as_view(),name='approve-application'),     
    path('application/<uuid:pk>/cancel/', ApplicationCancelView.as_view(), name='cancel-application'),
    path('application/<uuid:pk>/done/', JobDoneView.as_view(), name='job-done'),
    # path('make-payment/', MakePaymentView, name='make-payment'),
    # path("lipa-na-mpesa/", initiate_stk_push, name="lipa-na-mpesa"),
    # path("access_token/", get_access_token, name="access_token"),
    path('ratings/<profile_slug>/<application_slug>/ratings',ApplicantRatingsViews.as_view(),name="ratings"),
    path("complaints/<slug>", ComplaintsCreateView.as_view(), name="complaints")
    # path("checkout/<slug>", CheckoutView.as_view(), name="checkout")
     
]

Technical/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import handler404
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.defaults import page_not_found
from Page.sitemaps import StaticViewSitemap
from Job.sitemaps import JobSitemap
sitemaps={
    "jobs":JobSitemap,
    "static":StaticViewSitemap
}
urlpatterns = [
    path('admin/defender/', include('defender.urls')), # defender admin
    path('admin/', admin.site.urls),
    path("jobs/", include("Job.urls")),
    path("marketing/" , include("Marketing.urls")),
    path("blogs/", include("Blog.urls")),
    path("applications/", include("Application.urls")),
    path("", include("Page.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
#    path('mpesa/', include(mpesa_urls)),
    path("__debug__/", include("debug_toolbar.urls")),
    path("profile/", include("Account.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("accounts/", include("allauth.urls")),
    path('hijack/', include('hijack.urls')),
    path('sitemap.xml',sitemap,{"sitemaps":sitemaps},name="django.contrib.sitemaps.views.sitemap"),
    
    # path("hitcount/", include(("hitcount.urls", "hitcount"), namespace="hitcount")),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 ='Page.views.error_404'
handler500 ='Page.views.error_500'

Job/forms.py
from django.utils import timezone
from typing import Any

from ckeditor.widgets import CKEditorWidget
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

# from taggit.forms import *
from taggit.models import Tag

from Account.models import Rating

from .models import Complaints, Job, JobImage


class JobForm(forms.ModelForm):
    """Form definition for Job."""

    required_css_class = "required"
    images = forms.FileField(
        required=False,
        widget=forms.ClearableFileInput(
            attrs={"required": False, "class": "form-control images", "multiple": True}
        ),
    )
    tags = forms.ModelMultipleChoiceField(
        label="Tags",
        widget=forms.SelectMultiple(
            attrs={
                "class": "form-select form-control",
                "id": "job_tags",
                "required": True,
            }
        ),
        queryset=Tag.objects.all(),
    )

    content = forms.CharField(
        label="Descripion For The Job",
        widget=CKEditorWidget(attrs={"class": "form-control", "required": True}),
    )
    responsibility = forms.CharField(
        label="Responsibility For This Job",
        widget=CKEditorWidget(attrs={"class": "form-control", "required": True}),
    )
    qualification = forms.CharField(
        label="Qualification Needed For This Job",
        widget=CKEditorWidget(attrs={"class": "form-control", "required": True}),
    )

    skills = forms.CharField(
        label="Skills Needed For This Job",
        widget=CKEditorWidget(attrs={"class": "form-control", "required": True}),
    )

    class Meta:
        """Meta definition for Jobform."""

        model = Job
        fields = (
            "title",
            "category",
            "tags",
            "content",
            "responsibility",
            "qualification",
            "deadline",
            "job_end_time",
            "skills",
            "industry",
            "job_type",
            "seeker_type",
            "county",
            "location",
            "address",
        )
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "control-form title", "required": True}
            ),
            "category": forms.Select(
                attrs={"class": "control-select category", "required": True}
            ),
            "deadline": forms.DateTimeInput(
                attrs={
                    "class": "control-select deadline",
                    "required": True,
                    "type": "datetime-local",
                }
            ),
            "job_end_time": forms.DateTimeInput(
                attrs={
                    "class": "control-select job_end_time",
                    "required": True,
                    "type": "datetime-local",
                }
            ),
            "job_type": forms.Select(
                attrs={"class": "control-select job_type", "required": True}
            ),
            "seeker_type": forms.Select(
                attrs={"class": "control-select seeker_type", "required": True}
            ),
            "industry": forms.Select(
                attrs={"class": "control-select industry", "required": True}
            ),
            # "positions": forms.NumberInput(attrs={'min': '1', 'class': 'control-select positions', 'required': True}),
            "county": forms.Select(
                attrs={"class": "control-select county", "required": True}
            ),
            "location": forms.TextInput(
                attrs={"class": "control-form location", "required": True}
            ),
            "address": forms.TextInput(
                attrs={"class": "control-form address", "required": True}
            ),
        }

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        location = cleaned_data.get("location")
        address = cleaned_data.get("address")
        deadline = cleaned_data.get("deadline")
        job_end_time = cleaned_data.get("job_end_time")
        content = cleaned_data.get("content")
        responsibility = cleaned_data.get("responsibility")
        qualification = cleaned_data.get("qualification")
        skills = cleaned_data.get("skills")

        if title is not None and isinstance(title, str) and len(title) < 10:
            raise ValidationError(_("Title requires a minimum 10 characters required"), code="title")
        if location is not None and isinstance(location, str) and len(location) < 3:
            raise ValidationError(_("Location requires a minimum 3 characters required"), code="location")
        if address is not None and isinstance(address, str) and len(address) < 3:
            raise ValidationError(_("Address requires a minimum 3 characters required"), code="address")
        if content is not None and isinstance(content, str) and len(content) < 10:
            raise ValidationError(_("Description requires a minimum 10 characters required"), code="content")
        if (
            responsibility is not None
            and isinstance(responsibility, str)
            and len(responsibility) < 10
        ):
            raise ValidationError(
                _("Responsibility requires a minimum 10 characters required"), code="responsibility"
            )
        if (
            qualification is not None
            and isinstance(qualification, str)
            and len(qualification) < 10
        ):
            raise ValidationError(
                _("Minimum 10 characters required"), code="qualification"
            )
        if skills is not None and isinstance(skills, str) and len(skills) < 10:
            raise ValidationError(_("Skills requires a minimum 10 characters required"), code="skills")
        if deadline is not None and deadline < timezone.now():
            raise ValidationError(_("Deadline should be greater than now"))
        if job_end_time is not None and job_end_time <= timezone.now():
            raise ValidationError(_("Job Done date  should be greater than now"))
        if job_end_time and deadline is not None and job_end_time <deadline :
            raise ValidationError(_("Job Done time should be greater than deadline."))
            
    def clean_image(self):
        images = self.cleaned_data.get("images", False)
        if images:
            if images.size > 1*1024*1024:
                raise ValidationError(
                    _("Photo should be less than 5mbs"), code="invalid"
                )

        return images


class JobEditForm(forms.ModelForm):
    """Form definition for Job."""

    required_css_class = "required"
    images = forms.FileField(
        required=False,
        widget=forms.ClearableFileInput(
            attrs={"required": False, "class": "form-control images", "multiple": True}
        ),
    )
    tags = forms.ModelMultipleChoiceField(
        label="Tags",
        widget=forms.SelectMultiple(
            attrs={
                "class": "form-select form-control ",
                "id": "job_tags",
                "multiple": "multiple",
                "required": True,
            }
        ),
        queryset=Tag.objects.all(),
    )

    content = forms.CharField(
        label="Descripion For The Job",
        widget=CKEditorWidget(attrs={"class": "form-control", "required": True}),
    )
    responsibility = forms.CharField(
        label="Responsibility For This Job",
        widget=CKEditorWidget(attrs={"class": "form-control", "required": True}),
    )
    qualification = forms.CharField(
        label="Qualification Needed For This Job",
        widget=CKEditorWidget(attrs={"class": "form-control", "required": True}),
    )
    skills = forms.CharField(
        label="Skills Needed For This Job",
        widget=CKEditorWidget(attrs={"class": "form-control", "required": True}),
    )

    class Meta:
        """Meta definition for Jobform."""

        model = Job
        fields = (
            "title",
            "category",
            "tags",
            "content",
            "responsibility",
            "qualification",
            "deadline",
            "job_end_time",
            "skills",
            "industry",
            "job_type",
            "seeker_type",
            # "positions",
            "county",
            "location",
            "address",
        )
        label = {
            # "positions":"Available slots",
        }
        # def __init__(self,*args, **kwargs):
        #     super().__init__(*args, **kwargs)
        #     self.fields['title',].widget.attrs.update({'class':'form-label'})
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "control-form title", "required": True}
            ),
            "category": forms.Select(
                attrs={"class": "control-select category", "required": True}
            ),
            "deadline": forms.DateTimeInput(
                attrs={
                    "class": "control-select deadline",
                    "required": True,
                    "type": "datetime-local",
                }
            ),
            "job_end_time": forms.DateTimeInput(
                attrs={
                    "class": "control-select job_end_time",
                    "required": True,
                    "type": "datetime-local",
                }
            ),
            "job_type": forms.Select(
                attrs={"class": "control-select job_type", "required": True}
            ),
            "seeker_type": forms.Select(
                attrs={"class": "control-select seeker_type", "required": True}
            ),
            "industry": forms.Select(
                attrs={"class": "control-select industry", "required": True}
            ),
            # "positions": forms.NumberInput(attrs={'min': '1', 'class': 'control-select positions', 'required': True}),
            "county": forms.Select(

templates/jobs/add-jobs.html
{% extends 'base.html' %}
{% block title %} Post Job {% endblock title %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <div class="main-content">

                <div class="page-content">

                                   
 <div class="breadcrumbs overlay  mt-1" >
<div class="container">
<div class="row align-items-center">
<div class="col-lg-6 col-md-6 col-12">
<div class="breadcrumbs-content">
<h1 class="page-title">Post Job</h1>

</div>
</div>
<div class="col-lg-6 col-md-6 col-12">
<ul class="breadcrumb-nav float-sm-start float-lg-end float-md-end">
<li><a class="text-decoration-none" href="{% url 'home' %}">Home</a></li>
<li>Post Job</li>
</ul>
</div>
</div>
</div>
</div>
 {% if user.user_profile.firstname == "" and user.user_profile.lastname == "" %}
<br>

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
  <strong class="pl-2">Hello {{user.username}} !  </strong> Please complete your profile first for you to post job. <a href="{% url 'user-profile' user.user_profile.slug %}" class="pl-3 alert-link">Update Profile</a>.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div> 
        </div>
    </div>
</div>
<br>
{% endif %}
                    <!-- START JOB-LIST -->
                    <section class="section" style="padding-top:0px;padding-bottom:0px;"> 
                          <div class="add-blog">
                        <div class="container">
                          
                            <div class="row">
                            <div class="row justify-content-center pt-3 mt-3">
                                <div class="col-lg-7">
                                    <div class="section-title text-center mb-4 pb-2">
                                        <h4 class="title">Post Jobs Form</h4>
                                        <p class="text-muted mb-1">Post a job to tell us about your project. We'll quickly match you
                                            with the right freelancers.</p>
                                    </div>
                                </div><!--end col-->
                            </div><!--end row-->
                                <div class="col-lg-10 mx-auto">
                                     
                                   <form action="" method="post" enctype="multipart/form-data" class="p-5 mb-3 mt-4 border rounded-3 bg-white" onsubmit="return validateImageSize()">
    {% csrf_token %}
    {{form | crispy }}
     {% if user.user_profile.firstname == "" and user.user_profile.lastname == "" %}

     <br>

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
  <strong class="pl-2">Hello {{user.username}} !  </strong> Please complete your profile first for you to post job. <a href="{% url 'user-profile' user.user_profile.slug %}" class="pl-3 alert-link">Update Profile</a>.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div> 
        </div>
    </div>
</div>
<br>
{% else %}
    <div class="d-grid gap-2 col-6 mx-auto pt-2">
    <button type="submit" class="btn btn-success">Submit </button>
    </div>
    {% endif %}
</form> 
                                    
                                </div><!--end col-->

                            </div><!--end row-->

                    
                        </div><!--end container-->
                    </section>
                    <!-- END JOB-form -->

                    
                </div>
                <!-- End Page-content -->

                

               
</div>
                
            </div>
            <!-- end main content-->

    </div>


<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% block scripts %}
<script>
   $("#job_tags").select2(); 
</script>
<script>
function validateImageSize() {
        const fileInput = document.querySelector('#id_images'); // Replace with your image input field ID
        const maxSize = 1 * 1024 * 1024; // 4 MB (adjust this value as needed)

        if (fileInput.files.length > 0) {
            const fileSize = fileInput.files[0].size; // Size of the selected file in bytes

            if (fileSize > maxSize) {
                alert("File size is too large. Please select an image less than 4MB.");
                return false; // Prevent form submission
            }
        }

        return true; // Allow form submission if size is within limit
    }
</script>


{% endblock scripts %}
{% endblock content %}
    

templates/jobs/category-jobs.html
{% extends 'base.html' %}
{% block title %} Job Per Category {% endblock title %}
{% load humanize %}
{% block content %}
   <div>
        <div class="main-content">

                <div class="page-content">

                          <div class="breadcrumbs overlay  mt-1" >
<div class="container">
<div class="row align-items-center">
<div class="col-lg-6 col-md-6 col-12">
<div class="breadcrumbs-content">
<h1 class="page-title">{{caterory_name}}</h1>

</div>
</div>
<div class="col-lg-6 col-md-6 col-12">
<ul class="breadcrumb-nav float-sm-start float-lg-end float-md-end">
<li><a href="{% url 'home' %}">Home</a></li>
<li><a href="{% url 'jobs' %}">Jobs</a></li>
<li>{{caterory_name}}</li>
</ul>
</div>
</div>
</div>
</div>
                    <!-- START JOB-LIST -->
                    <section class="section">
                        <div class="container">
                            {% comment %} {% include 'includes/search.html' %} {% endcomment %}
                            
                            <div class="row">
                               {% for job in jobs %}
                                <div class="col-lg-6">
                                    
                                    <div class="job-box bookmark-post card mt-5">
                                                <div class="p-4">
                                                    <div class="row">
                                                        {% comment %} <div class="col-lg-1">
                                                            <a href="company-details.html"><img src="{{job.user.user_profile.profile.url}}" alt="..." class="img-fluid rounded-3"></a>
                                                        </div><!--end col--> {% endcomment %}
                                                        <div class="col-lg-12">
                                                            <div class="mt-3 mt-lg-0">
                                                                <h5 class="fs-17 mb-1"><a href="{{job.get_absolute_url}}" class="text-dark text-decoration-none">{{job.title | truncatewords:10}}</a> </h5>
                                                                <ul class="list-inline mb-0">
                                                                    <li class="list-inline-item">
                                                                        <p class="text-muted fs-14 mb-0"><i class="uil uil-user"></i> <a class="text-dark text-decoration-none" href="{% url 'user-jobs' job.user.username %}">{{job.user.user_profile.firstname}} {{job.user.user_profile.lastname}}</a> </p>
                                                                    </li>
                                                                    <li class="list-inline-item">
                                                                        <p class="text-muted fs-14 mb-0"><i class="mdi mdi-map-marker"></i> {{job.county}} ,{{job.location}},{{job.address}}</p>
                                                                    </li>
                                                                    <li class="list-inline-item">
                                                                        <p class="text-muted fs-14 mb-0"><i class="uil uil-calender"></i> {{job.created |naturaltime}}</p>
                                                                    </li>
                                                                </ul>
                                                                <div class="mt-2"> 
                                                                    
                                                                    <span class="badge bg-soft-success mt-1">Deadline: {{job.deadline}}</span>
                                                                    <span class="badge bg-soft-warning mt-1">open to: {{job.seeker_type}}</span>
                                                                    <span class="badge bg-soft-info mt-1">{{job.job_type}}</span>
                                                                </div>
                                                            </div>
                                                        </div><!--end col-->
                                                    </div><!--end row-->
                                                   
                                                </div>
                                                <div class="p-3 bg-light">
                                                    <div class="row justify-content-between">
                                                        <div class="col-md-8">
                                                            <div>
                                                                <ul class="list-inline mb-0">
                                                                    <li class="list-inline-item"><i class="uil uil-tag"></i> Tags :</li>{% for tag in job.tags.all %}
                                                                    <li class="list-inline-item"><a href="{% url 'tag-jobs' tag.slug %}" class="primary-link text-muted text-decoration-none">{{ tag.name }}</a>,</li>
                                                                   
                                                                    {% endfor %}
                                                                </ul>
                                                            </div>
                                                        </div>
                                                        <!--end col-->
                                                        <div class="col-md-3">
                                                            
                                                            {% if job.user != request.user %}
                                                                <div class="text-md-end">
                                                                <a href="{% url 'applications:apply-job' job.slug %}"  class="primary-link text-decoration-none">Apply Now <i class="mdi mdi-chevron-double-right"></i></a>
                                                            </div>
                                                            {% endif %}
                                                                
                                                            
                                                        </div>
                                                        <!--end col-->
                                                    </div>
                                                    <!--end row-->
                                                </div>
                                            </div>
                                    
                                </div><!--end col-->
                               {% empty %} 
                                <div class="col-lg-12">
                                    
                                    
                                    <div class="job-box  card mt-5">
                                                <div class="p-4">
                                                    <p> No jobs found! </p>
                                                </div>
                                                
                                            </div>
                                </div><!--end col-->
                               {% endfor %}
                                <div class="col-lg-6">
                                    
                                    
                                    
                                </div><!--end col-->

                            </div><!--end row-->

                              <!-- End Job-list -->
                                        <div class="row">
                                            <div class="col-lg-12 mt-4 pt-2">
                                                <nav aria-label="Page navigation example">
                                                    <ul class="pagination job-pagination mb-0 justify-content-center">
                                                         {% if page_obj.has_previous %}
                                                        <li class="page-item ">
                                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">
                                                                <i class="mdi mdi-chevron-double-left fs-15"></i>
                                                            </a>
                                                        </li>
                                                         {% if page_obj.number > 3 %}
    <a class="page-link" href="?page=1">1</a>
    {% if page_obj.number > 4 %}
      <span>.....</span>
    {% endif %}
  {% endif %}
{% endif %}

{% for num in page_obj.paginator.page_range %}
  {% if page_obj.number == num %}

                                                        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}

                                                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                                        {% endif %}
{% endfor %}

{% if page_obj.has_next %}
  {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
    <span>...</span> 

                                                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                                                       {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
                                                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                                                         {% endif %}
                                                        <li class="page-item">
                                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                                                <i class="mdi mdi-chevron-double-right fs-15"></i>
                                                            </a>
                                                        </li>
                                                        {% endif %}
                                                    </ul>
                                                </nav>
                                            </div><!--end col-->
                                        </div><!-- end row -->
                    
                        </div><!--end container-->
                    </section>
                    <!-- END JOB-LIST -->

                    
                </div>
                <!-- End Page-content -->

                

               

                
            </div>
            <!-- end main content-->

    </div>

{% endblock content %}
    